### ISSUE TITLE
please update to version 2024.6.18

### ISSUE THREAD

**Issue by engix3** [Tommy-XL/Unlock-dlekS-ehT#2]

**Comment by Tommy-XL** [comment]
I'm working on it, the current version causes problems in the lobby when selecting this map

**Comment by Tommy-XL** [comment]
Bruh, sorry for the long wait, lol

It mod supports the latest AU versions
https://github.com/Tommy-XL/Unlock-dlekS-ehT/releases/tag/v1.1.0
